// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywgvluvzftterkuswcsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3Z3ZsdXZ6ZnR0ZXJrdXN3Y3NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3Mjc4ODcsImV4cCI6MjA2MDMwMzg4N30.7eUK12eCh8Z5Vu5eNtylnPAEFDpnM_ycUcUQZoH7Jw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);